---
include:
  - project: shore/ci-templates
    file: templates/pre-commit.yml
  - project: shore/ci-templates
    file: templates/docker.yml

stages:
  - test
  - build
  - deploy

build:
  extends: .docker-build-shore
  tags: [ns4.shore.co.il]

push-shore:
  extends: .docker-push
  tags: [ns4.shore.co.il]
  variables:
    FULL_IMAGE: "registry.shore.co.il/$IMAGE:$TAG"

push-hub:
  extends: .docker-push
  tags: [ns4.shore.co.il]
  variables:
    FULL_IMAGE: "registry.hub.docker.com/$IMAGE:$TAG"
