# vim:ff=unix ts=2 sw=2 ai expandtab
---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: detect-private-key
      - id: trailing-whitespace
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.17.0
    hooks:
      - id: yamllint
  - repo: https://github.com/amperser/proselint
    rev: 0.10.1
    hooks:
      - id: proselint
        types: [plain-text]
        exclude: LICENSE
  - repo: https://git.shore.co.il/nimrod/docker-pre-commit.git
    rev: v0.3.0
    hooks:
      - id: hadolint
  - repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
      - id: black
        args:
          - |
              --line-length=79
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.8
    hooks:
      - id: flake8
        args:
          - |-
            --max-line-length=79
        additional_dependencies:
          - flake8-bugbear
