#!/bin/sh
set -eux
template /var/awslogs/etc/awslogs.conf.j2 > /tmp/config
if [ -z "${AWS_DEFAULT_REGION:-}" ]
then
    AWS_DEFAULT_REGION="$(deduce-aws-region)"
    export AWS_DEFAULT_REGION
fi
eval exec "$@"
